spring.application.name: siatest-task-simple
spring.application.cnname: 任务调度执行器
#应用端口号
server.port: 12129

sia:
  task:
    zookeeper:
      host-list: 127.0.0.1:2181
      root-path: SkyWorldOnlineTask
      sleep-ms-between-retries: 5000
      connect-lost-retry-times: 10
      max-wait-seconds: 60
      root-auth: SIA:SkyWorld
      create-auth: guest:guest
      digest-auth: digest

logging.file: ./logs/${spring.application.name}.log